
name: 'adwords'
version: '1.1'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  adwords:
    stitch:

      vars:
        criteria_performance_report:    #"schema.table"
        click_performance_report:       #"schema.table"
        final_url_performance_report:   #"schema.table"
        ads_table:                      #"schema.table"
        ad_groups_table:                #"schema.table"
        accounts_table:                 #"schema.table"
        campaigns_table:                #"schema.table"

        adapter_value:                #url or criteria
        
