
name: 'adwords'
version: '1.1'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  adwords:
    stitch:
      enabled: true
      materialized: view
      vars:
        criteria_performance_report:    #"schema.table"
        click_performance_report:       #"schema.table"
