adwords_campaign_performance:
    constraints:
        unique:
            - campaign_id
        not_null:
            - campaign_id

adwords_click_performance:
    constraints:
        unique:
            - gclid
        not_null:
            - gclid

adwords_criteria_performance:
    constraints:
        unique:
            - criteria_id
        not_null:
            - criteria_id
