version: 2

models:
  - name: adwords_click_performance
    columns:
        - name: gclid
          tests:
              - unique
              - not_null
              
  - name: adwords_criteria_performance
    columns:
        - name: id
          tests:
              - unique
              - not_null
              
  - name: adwords_url_performance
    columns:
        - name: id
          tests:
              - unique
              - not_null
              
  - name: adwords_accounts
    columns:
        - name: account_id
          tests:
              - unique
              - not_null
              
  - name: adwords_ad_groups
    columns:
        - name: ad_group_id
          tests:
              - unique
              - not_null
              
  - name: adwords_ads
    columns:
        - name: ad_id
          tests:
              - unique
              - not_null
              
  - name: adwords_campaigns
    columns:
        - name: campaign_id
          tests:
              - unique
              - not_null