ADWORDS_CLICK_PERFORMANCE:
    constraints:
        unique:
            - gclid
        not_null:
            - gclid

ADWORDS_CRITERIA_PERFORMANCE:
    constraints:
        unique:
            - id
        not_null:
            - id
